//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheCardEditor.Main.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AgGridResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AgGridResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheCardEditor.Main.Core.AgGridResources", typeof(AgGridResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ag-row-aquamarine.
        /// </summary>
        public static string AquamarineGridRow {
            get {
                return ResourceManager.GetString("AquamarineGridRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ag-row-green.
        /// </summary>
        public static string GreenGridRow {
            get {
                return ResourceManager.GetString("GreenGridRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ag-row-grey.
        /// </summary>
        public static string GreyGridRow {
            get {
                return ResourceManager.GetString("GreyGridRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ag-row-khaki.
        /// </summary>
        public static string KhakiGridRow {
            get {
                return ResourceManager.GetString("KhakiGridRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ag-row-nocolor.
        /// </summary>
        public static string NoColorRow {
            get {
                return ResourceManager.GetString("NoColorRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ag-row-purple.
        /// </summary>
        public static string PurpleGridRow {
            get {
                return ResourceManager.GetString("PurpleGridRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ag-row-red.
        /// </summary>
        public static string RedGridRow {
            get {
                return ResourceManager.GetString("RedGridRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ag-row-yellow.
        /// </summary>
        public static string YellowGridRow {
            get {
                return ResourceManager.GetString("YellowGridRow", resourceCulture);
            }
        }
    }
}
