//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheCardEditor.DataModel.Migrations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DatabaseMigrations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DatabaseMigrations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TheCardEditor.DataModel.Migrations.DatabaseMigrations", typeof(DatabaseMigrations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE &quot;ApplicationData&quot; (
        ///	&quot;Id&quot;	INTEGER NOT NULL,
        ///	&quot;Name&quot;	TEXT NOT NULL,
        ///	&quot;Value&quot;	TEXT NOT NULL,
        ///	PRIMARY KEY(&quot;Id&quot; AUTOINCREMENT)
        ///);
        ///INSERT INTO &quot;main&quot;.&quot;ApplicationData&quot;(&quot;Id&quot;,&quot;Name&quot;,&quot;Value&quot;) VALUES (1,&apos;Version&apos;,&apos;1.2.0&apos;);
        ///ALTER TABLE &quot;main&quot;.&quot;CardSet&quot; ADD COLUMN 	&quot;Zoom&quot;	REAL NOT NULL DEFAULT 100.0;.
        /// </summary>
        public static string _1_2_0 {
            get {
                return ResourceManager.GetString("1.2.0", resourceCulture);
            }
        }
    }
}
